<a href="https://colab.research.google.com/github/leandroclv/polars_alura/blob/main/Polars_manipulando_tabelas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import polars as pl

In [9]:
url = '//content/drive/MyDrive/Colab Notebooks/Análise de Dados com Polars: O Novo Padrão do Python - Alura/dadocurso.csv'
df = pl.read_csv(url)

In [11]:
df.head(3)

shape: (3, 14)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Região     ┆ País   ┆ Tipo de    ┆ Canal de  ┆ … ┆ Custo     ┆ Receita   ┆ Custo     ┆ Lucro     │
│ ---        ┆ ---    ┆ Item       ┆ Venda     ┆   ┆ Unitário  ┆ Total     ┆ Total     ┆ Total     │
│ str        ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆        ┆ str        ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Australia  ┆ Palau  ┆ Office     ┆ Online    ┆ … ┆ 524.96    ┆ 1.2508e6  ┆ 1.2604e6  ┆ -9584.792 │
│ and        ┆        ┆ Supplies   ┆           ┆   ┆           ┆           ┆           ┆           │
│ Oceania    ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ Europe     ┆ Poland ┆ Beverages  ┆ Online    ┆ … ┆ 31.79     ┆ 354546.4  ┆ 296918.6  ┆ 57627.8   │
│ North      ┆ Canada ┆ Cereal     ┆ Online    ┆ … ┆ 117.11    ┆ 16949.68  ┆ 12062.33  ┆ 4887.35   │
│ America    ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
df.dtypes

[String,
 String,
 String,
 String,
 String,
 String,
 Int64,
 String,
 Int64,
 Float64,
 Float64,
 Float64,
 Float64,
 Float64]

In [15]:
df.describe()

shape: (9, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ Região    ┆ País      ┆ Tipo de   ┆ … ┆ Custo     ┆ Receita   ┆ Custo     ┆ Lucro    │
│ ---       ┆ ---       ┆ ---       ┆ Item      ┆   ┆ Unitário  ┆ Total     ┆ Total     ┆ Total    │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 5000000   ┆ 5000000   ┆ 5000000   ┆ … ┆ 5e6       ┆ 5e6       ┆ 5e6       ┆ 5e6      │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ 187.65599 ┆ 1.1439e6  ┆ 938378.12 ┆ 205508.4 │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆ 2412      ┆ 25247    │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 175.70137 ┆ 1.3158e6  ┆ 1.1501e6  ┆ 451094.2 │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆ 54368    │
│ min       ┆ Asia      ┆ Afghanist ┆ Baby Food ┆ … ┆ 6.92      ┆ 7.464     ┆ 6.92      ┆ -271780. │
│           ┆           ┆ an        ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 56.67     ┆ 231366.2  ┆ 161925.12 ┆ 5065.57  │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 117.11    ┆ 658009.72 ┆ 467712.0  ┆ 80190.0  │
│           ┆           ┆           ┆           ┆   ┆           ┆ 8         ┆           ┆          │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 364.69    ┆ 1.5568e6  ┆ 1.1974e6  ┆ 258412.7 │
│ max       ┆ Sub-Sahar ┆ Zimbabwe  ┆ Vegetable ┆ … ┆ 524.96    ┆ 1.002405e ┆ 5.2496e6  ┆ 4.99865e │
│           ┆ an Africa ┆           ┆ s         ┆   ┆           ┆ 7         ┆           ┆ 6        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
df.select(pl.col(pl.Int64, pl.Float64)).describe()

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ ID do      ┆ Unidades   ┆ Preço     ┆ Custo     ┆ Receita   ┆ Custo     ┆ Lucro     │
│ ---        ┆ Pedido     ┆ Vendidas   ┆ Unitário  ┆ Unitário  ┆ Total     ┆ Total     ┆ Total     │
│ str        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 5e6        ┆ 5e6        ┆ 5e6       ┆ 5e6       ┆ 5e6       ┆ 5e6       ┆ 5e6       │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 5.4989e8   ┆ 4999.99106 ┆ 266.19061 ┆ 187.65599 ┆ 1.1439e6  ┆ 938378.12 ┆ 205508.42 │
│            ┆            ┆ 1          ┆ 6         ┆ 1         ┆           ┆ 2412      ┆ 5247      │
│ std        ┆ 2.5978e8   ┆ 2886.78700 ┆ 217.01527 ┆ 175.70137 ┆ 1.3158e6  ┆ 1.1501e6  ┆ 451094.25 │
│            ┆            ┆ 7          ┆ 3         ┆ 9         ┆           ┆           ┆ 4368      │
│ min        ┆ 1.00000321 ┆ 1.0        ┆ 9.33      ┆ 6.92      ┆ 7.464     ┆ 6.92      ┆ -271780.0 │
│            ┆ e8         ┆            ┆           ┆           ┆           ┆           ┆           │
│ 25%        ┆ 3.24965131 ┆ 2500.0     ┆ 109.28    ┆ 56.67     ┆ 231366.2  ┆ 161925.12 ┆ 5065.57   │
│            ┆ e8         ┆            ┆           ┆           ┆           ┆           ┆           │
│ 50%        ┆ 5.49764287 ┆ 4999.0     ┆ 205.7     ┆ 117.11    ┆ 658009.72 ┆ 467712.0  ┆ 80190.0   │
│            ┆ e8         ┆            ┆           ┆           ┆ 8         ┆           ┆           │
│ 75%        ┆ 7.74837243 ┆ 7500.0     ┆ 437.2     ┆ 364.69    ┆ 1.5568e6  ┆ 1.1974e6  ┆ 258412.7  │
│            ┆ e8         ┆            ┆           ┆           ┆           ┆           ┆           │
│ max        ┆ 9.99999892 ┆ 10000.0    ┆ 668.27    ┆ 524.96    ┆ 1.002405e ┆ 5.2496e6  ┆ 4.99865e6 │
│            ┆ e8         ┆            ┆           ┆           ┆ 7         ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [17]:
df.null_count()

shape: (1, 14)
┌────────┬──────┬─────────┬──────────┬───┬──────────┬─────────┬─────────────┬─────────────┐
│ Região ┆ País ┆ Tipo de ┆ Canal de ┆ … ┆ Custo    ┆ Receita ┆ Custo Total ┆ Lucro Total │
│ ---    ┆ ---  ┆ Item    ┆ Venda    ┆   ┆ Unitário ┆ Total   ┆ ---         ┆ ---         │
│ u32    ┆ u32  ┆ ---     ┆ ---      ┆   ┆ ---      ┆ ---     ┆ u32         ┆ u32         │
│        ┆      ┆ u32     ┆ u32      ┆   ┆ u32      ┆ u32     ┆             ┆             │
╞════════╪══════╪═════════╪══════════╪═══╪══════════╪═════════╪═════════════╪═════════════╡
│ 0      ┆ 0    ┆ 0       ┆ 0        ┆ … ┆ 0        ┆ 0       ┆ 0           ┆ 0           │
└────────┴──────┴─────────┴──────────┴───┴──────────┴─────────┴─────────────┴─────────────┘

In [18]:
nan_count = {
    col: (
        (df[col].is_nan().sum() if df[col].dtype in (pl.Int64, pl.Float64) else 0)
        + df[col].is_null().sum()
    )
    for col in df.columns
}

In [19]:
nan_count

{'Região': 0,
 'País': 0,
 'Tipo de Item': 0,
 'Canal de Venda': 0,
 'Prioridade do Pedido': 0,
 'Data do Pedido': 0,
 'ID do Pedido': 0,
 'Data de Envio': 0,
 'Unidades Vendidas': 0,
 'Preço Unitário': 0,
 'Custo Unitário': 0,
 'Receita Total': 0,
 'Custo Total': 0,
 'Lucro Total': 0}